# Generated by Django 2.2.4 on 2019-09-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.CharField(default='', max_length=50)),
                ('sucursalId', models.CharField(default='', max_length=50)),
                ('fridge', models.CharField(default='', max_length=50)),
                ('fridge_door', models.CharField(default='', max_length=50)),
                ('tier', models.CharField(default='', max_length=50)),
                ('sensor', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
