# Generated by Django 2.2.4 on 2019-09-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='deviceId',
            field=models.CharField(default='', max_length=50),
        ),
    ]
