# Generated by Django 2.2.4 on 2019-09-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_devicedata_deviceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='porcentage',
            field=models.CharField(default='', max_length=20),
        ),
    ]
