# Generated by Django 2.2.4 on 2019-09-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_devicedata_porcentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicedata',
            name='distance',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='latitude',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='devicedata',
            name='longitude',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
