# Generated by Django 2.2.4 on 2019-09-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus2', '0007_auto_20190912_1304'),
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='MenusParaUsuario',
            field=models.ManyToManyField(to='menus2.Menu'),
        ),
    ]
