# Generated by Django 2.2.4 on 2019-09-02 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(default='', max_length=50)),
                ('submenu', models.CharField(default='', max_length=50)),
                ('tipo', models.CharField(default='', max_length=50)),
                ('visible', models.CharField(default='', max_length=2)),
                ('pagina', models.CharField(default='', max_length=50)),
                ('id_suc', models.IntegerField(default=datetime.datetime(2019, 1, 1, 0, 0))),
                ('fecha_modificacion', models.DateTimeField(default=datetime.datetime(2019, 9, 2, 12, 55, 27, 144524))),
                ('usuario_modifico', models.CharField(default='', max_length=45)),
                ('icono', models.CharField(default='', max_length=50)),
                ('ic_doc', models.IntegerField(null=True)),
            ],
        ),
    ]
