# Generated by Django 2.2.4 on 2019-09-06 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus2', '0002_auto_20190904_1637'),
        ('menus2', '0002_auto_20190905_1541'),
    ]

    operations = [
    ]
