# Generated by Django 2.2.4 on 2019-09-09 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus2', '0002_auto_20190905_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(default='', max_length=45)),
                ('id_men', models.IntegerField(default=0)),
                ('fecha_modificacion', models.DateTimeField(default=datetime.datetime(2019, 9, 9, 12, 46, 33, 673210))),
                ('usuario_modifico', models.CharField(default='', max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPermisos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuperUsuario', models.CharField(max_length=100)),
                ('usuperPermiso', models.CharField(max_length=50)),
                ('usuperCreaUsuario', models.CharField(max_length=50)),
                ('usuperFechaCreacion', models.DateTimeField(default=datetime.datetime(2019, 9, 9, 12, 46, 33, 674207))),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='fecha_modificacion',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 9, 12, 46, 33, 672213)),
        ),
    ]
