# Generated by Django 2.2.4 on 2019-09-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus2', '0003_merge_20190906_1926'),
        ('menus2', '0004_auto_20190909_1350'),
    ]

    operations = [
    ]
