# Generated by Django 2.2.4 on 2019-09-12 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus2', '0005_merge_20190910_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='MenusParaUsuario',
            field=models.ManyToManyField(to='menus2.Menu'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='fecha_modificacion',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 12, 13, 0, 7, 640032)),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_modificacion',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 12, 13, 0, 7, 641030)),
        ),
        migrations.AlterField(
            model_name='usuariopermisos',
            name='usuperFechaCreacion',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 12, 13, 0, 7, 643051)),
        ),
    ]
