# Generated by Django 2.2.4 on 2019-09-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus2', '0007_auto_20190912_1304'),
        ('menus2', '0006_auto_20190912_1843'),
    ]

    operations = [
    ]
