# Generated by Django 2.2.4 on 2019-09-12 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus2', '0017_auto_20190912_2148'),
        ('menus2', '0009_auto_20190912_1522'),
    ]

    operations = [
    ]
